apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: k8s-demo-namespace
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: hello-app
          # Jenkins overwrites this tag each build: v1.0.${BUILD_NUMBER}
          image: ghcr.io/ashmit-gupta/k8-test-project:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
